name: MLOps Quality Check

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Installer Python
        run: uv python install 3.11

      - name: Installer les dépendances
        run: uv sync --frozen

      - name: Lancer les tests unitaires
        run: uv run pytest

      - name: Vérifier le Build Docker
        run: |
          docker build -t maintenance-api:test .